from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

# from flask_bcrypt import Bcrypt
# from flask_login import LoginManager


app = Flask(__name__)
# Generated by python secrets
app.config["SECRET_KEY"] = "a30cdd326e59446444b78cdc97800aea"
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///site.db"
db = SQLAlchemy(app)
migrate = Migrate(app, db, compare_type=True)
# bcrypt = Bcrypt(app)
# login_manager = LoginManager(app)
# login_manager.login_view = 'login'
# login_manager.login_message_category = 'info'

from app import routes
