"""empty message

Revision ID: 0d7e0a852b59
Revises: 
Create Date: 2023-03-10 16:03:59.600853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7e0a852b59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_class', schema=None) as batch_op:
        batch_op.alter_column('class_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=3),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_class', schema=None) as batch_op:
        batch_op.alter_column('class_type',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
