"""empty message

Revision ID: 454f7eef4337
Revises: 41ddf66cf913
Create Date: 2023-03-10 17:18:00.859064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454f7eef4337'
down_revision = '41ddf66cf913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('test_field')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_field', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
